import sys
from pathlib import Path

try:
    from PyInstaller.utils.hooks import collect_data_files
except ImportError:
    collect_data_files = None


def main() -> int:
    """Build a single-file Windows executable using PyInstaller.

    Usage:
        python build_onefile.py

    Notes:
        - Ensure you have PyInstaller installed: pip install pyinstaller
        - Output will be placed in ./dist

    Root cause of Qt6 DLL errors (icuuc.dll / WinError 127):
        PyInstaller picks up icuuc.dll / icudt*.dll from the conda environment.
        PyQt6-Qt6 was built against Windows' built-in ICU stub (~37 KB in
        System32), not the full ICU library (~2.7 MB) conda ships.  The ABI
        mismatch causes ERROR_PROC_NOT_FOUND when Qt6Core.dll loads.
        Same issue for ucrtbase.dll / api-ms-win-* from an older Windows SDK.

        Fix: generate a .spec file and filter a.binaries directly in Python
        before PyInstaller packs the archive.  This is the only reliable
        build-time approach for --onefile.

        Note on textwrap.dedent + f-strings:
        Do NOT use textwrap.dedent() on an f-string that interpolates content
        with different leading whitespace.  dedent() inspects the minimum
        leading whitespace across ALL lines AFTER interpolation; dynamically-
        generated lines (e.g. *collect_submodules(...)) with fewer leading
        spaces lower that minimum, causing under-stripping and IndentationError
        in the generated spec file.  Build spec lines explicitly instead.
    """

    try:
        from PyInstaller.__main__ import run as pyinstaller_run
    except Exception as e:
        print("PyInstaller is not installed or failed to import.")
        print("Install it with: pip install pyinstaller")
        print(f"Import error: {e}")
        return 1

    if collect_data_files is None:
        print("collect_data_files is not available. PyInstaller hooks may be missing.")
        return 1

    project_root = Path(__file__).resolve().parent
    entry = project_root / "main.py"

    if not entry.exists():
        print(f"Entry file not found: {entry}")
        return 1

    src_path = str(project_root / "src")
    assets_dir = project_root / "assets"
    icon_path = assets_dir / "icon.ico"

    # PyQt6 modules actually used by this application.
    used_qt_modules = [
        "PyQt6.QtCore",
        "PyQt6.QtGui",
        "PyQt6.QtWidgets",
        "PyQt6.QtSvg",
    ]

    # Qt6 addons that are definitely NOT used.
    unused_qt_modules = [
        "PyQt6.QtNetwork",
        "PyQt6.QtMultimedia",
        "PyQt6.QtMultimediaWidgets",
        "PyQt6.QtWebEngineWidgets",
        "PyQt6.QtWebEngineCore",
        "PyQt6.QtWebChannel",
        "PyQt6.Qt3DCore",
        "PyQt6.Qt3DRender",
        "PyQt6.Qt3DInput",
        "PyQt6.Qt3DLogic",
        "PyQt6.Qt3DAnimation",
        "PyQt6.Qt3DExtras",
        "PyQt6.QtBluetooth",
        "PyQt6.QtNfc",
        "PyQt6.QtPositioning",
        "PyQt6.QtLocation",
        "PyQt6.QtPrintSupport",
        "PyQt6.QtQml",
        "PyQt6.QtQuick",
        "PyQt6.QtQuickWidgets",
        "PyQt6.QtRemoteObjects",
        "PyQt6.QtSensors",
        "PyQt6.QtSerialPort",
        "PyQt6.QtSql",
        "PyQt6.QtTest",
        "PyQt6.QtXml",
        "imageio",
        "imageio_ffmpeg",
    ]

    # ------------------------------------------------------------------ #
    # Build spec file content as a list of explicit lines.                #
    # ------------------------------------------------------------------ #
    # Each element is a string that will be joined with "\n".
    # Using a list avoids the textwrap.dedent pitfall described above.

    # hiddenimports block
    hidden_lines = [
        "    'PyQt6.sip',",
        "    'shiboken6',",
        "    'matplotlib.backends.backend_agg',",
        "    'matplotlib.backends.backend_pdf',",
        "    'matplotlib.backends.backend_svg',",
    ] + [f"    *collect_submodules({m!r})," for m in used_qt_modules] + [f"    *collect_submodules('matplotlib'),"]

    icon_arg = f"    icon={str(icon_path)!r}," if icon_path.exists() else ""
    matplotlib_datas = collect_data_files('matplotlib')
    if assets_dir.exists():
        datas_list = [(str(assets_dir), 'assets')] + matplotlib_datas
    else:
        datas_list = matplotlib_datas
    datas_arg = f"    datas={datas_list!r},"
    entry_arg = f"    [{str(entry)!r}],"
    pathex_arg = f"    pathex=[{src_path!r}],"
    excludes_arg = f"    excludes={unused_qt_modules!r},"

    spec_lines = [
        "# Auto-generated by build_onefile.py — do not edit manually.",
        "# Re-run build_onefile.py to regenerate.",
        "from PyInstaller.utils.hooks import collect_submodules, collect_dynamic_libs, collect_data_files",
        "from PyInstaller.building.build_main import Analysis, PYZ, EXE, TOC",
        "",
        "block_cipher = None",
        "",
        "a = Analysis(",
        entry_arg,
        pathex_arg,
        "    binaries=list(collect_dynamic_libs('PyQt6')),",
        datas_arg,
        "    hiddenimports=[",
        *hidden_lines,
        "    ],",
        "    hookspath=[],",
        "    hooksconfig={},",
        "    runtime_hooks=[],",
        excludes_arg,
        "    win_no_prefer_redirects=False,",
        "    win_private_assemblies=False,",
        "    cipher=block_cipher,",
        "    noarchive=False,",
        ")",
        "",
        "# Strip DLLs that shadow incompatible system copies (WinError 127).",
        "# icuuc.dll/icudt*.dll: conda full ICU vs Windows built-in ICU stub.",
        "# ucrtbase.dll/api-ms-win-*: stale SDK copies shadowing system UCRT.",
        "def _is_rogue(dest_name):",
        "    n = dest_name.lower()",
        "    return (",
        "        n.startswith('api-ms-win-')",
        "        or n == 'ucrtbase.dll'",
        "        or n.startswith('icu')",
        "    )",
        "",
        "removed = [(n, p, t) for n, p, t in a.binaries if _is_rogue(n)]",
        "for n, _, _ in removed:",
        "    print(f'  [spec] Excluded rogue DLL: {n}')",
        "a.binaries = TOC([(n, p, t) for n, p, t in a.binaries if not _is_rogue(n)])",
        "print(f'[spec] Excluded {len(removed)} rogue DLL(s) from the archive.')",
        "",
        "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)",
        "",
        "exe = EXE(",
        "    pyz,",
        "    a.scripts,",
        "    a.binaries,",
        "    a.zipfiles,",
        "    a.datas,",
        "    [],",
        "    name='ImageLayoutManager',",
        "    debug=False,",
        "    bootloader_ignore_signals=False,",
        "    strip=False,",
        "    upx=False,",
        "    upx_exclude=[],",
        "    runtime_tmpdir='.',",
        "    console=False,",
        "    disable_windowed_traceback=False,",
        "    argv_emulation=False,",
        "    target_arch=None,",
        "    codesign_identity=None,",
        "    entitlements_file=None,",
        icon_arg,
        ")",
    ]

    spec_content = "\n".join(spec_lines) + "\n"

    build_dir = project_root / "build"
    build_dir.mkdir(parents=True, exist_ok=True)
    spec_path = build_dir / "ImageLayoutManager_onefile.spec"
    spec_path.write_text(spec_content, encoding="utf-8")
    print(f"Generated spec file: {spec_path}")

    # Run PyInstaller on the generated spec file.
    args = [
        "--noconfirm",
        "--distpath", str(project_root / "dist"),
        "--workpath", str(project_root / "build" / "ImageLayoutManager"),
        str(spec_path),
    ]
    print("Running PyInstaller on spec file:")
    for a in args:
        print(f"  {a}")

    pyinstaller_run(args)

    dist_exe = project_root / "dist" / "ImageLayoutManager.exe"
    if dist_exe.exists():
        print(f"\nBuild OK: {dist_exe}")
        return 0

    print("Build finished, but executable was not found at expected path:")
    print(dist_exe)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
