name: imagelayout
channels:
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - PyQt6
      - PyQt6-Qt6
      - PyQt6-sip
      - Pillow
      - matplotlib
      - PyMuPDF
      - pyinstaller
