"""
SVG exporter for ImageLayoutManager.

Uses QSvgGenerator as the QPainter target so that the exact same
_paint_scene() pipeline that drives raster and PDF export also drives
SVG output.  This guarantees:

  • All element positions are identical to raster/PDF — they all come
    from LayoutEngine.calculate_layout(), scaled by the same factor.
  • SVG source images are rendered as embedded vector content
    (QSvgRenderer → QPainter → QSvgGenerator preserves vector data).
  • Text renders as SVG <text> nodes (not rasterised outlines).
  • Clip paths, rotations, and blending are handled by Qt natively.

Resolution: the project DPI is forwarded to QSvgGenerator so the
output SVG carries the correct physical dimensions in mm.
"""

from __future__ import annotations

import os
from typing import Optional

from PyQt6.QtCore import QRectF, QSize
from PyQt6.QtGui import QPainter, QColor
from PyQt6.QtSvg import QSvgGenerator

from src.model.data_model import Project
from src.model.layout_engine import LayoutEngine
from src.export.image_exporter import ImageExporter


class SvgExporter:
    """Export a Project to an SVG file."""

    @staticmethod
    def export(project: Project, output_path: str) -> None:
        """
        Render *project* to *output_path* as an SVG file.

        The output dimensions and DPI match the project settings exactly.
        If project.export_region is set the SVG is clipped to that region,
        mirroring the behaviour of the raster and PDF exporters.
        """
        layout_result = LayoutEngine.calculate_layout(project)

        # ── Resolve export region ─────────────────────────────────────────
        export_region = getattr(project, "export_region", None)
        if export_region is not None:
            page_w_mm = export_region.w_mm
            page_h_mm = export_region.h_mm
            region_dx_mm = export_region.x_mm
            region_dy_mm = export_region.y_mm
        else:
            page_w_mm = project.page_width_mm
            page_h_mm = project.page_height_mm
            region_dx_mm = 0.0
            region_dy_mm = 0.0

        # ── Coordinate scale ──────────────────────────────────────────────
        # QSvgGenerator must be run at 72 DPI (Qt's font reference DPI) so that
        # a font set to P points is emitted as exactly P SVG user-units — no
        # extra DPI inflation.  If we used project.dpi here, Qt would emit
        # font-size = P * (dpi/72) SVG units AND the painter.scale() transform
        # in _draw_text would scale them again, producing text that is
        # (dpi/72)× too large compared to raster/PDF output.
        #
        # Physical dimensions remain correct: the SVG viewBox is in 72-DPI
        # "pixels" and the generator's resolution=72 tells SVG viewers that
        # 1 user-unit = 1/72 inch, so the canvas physical size matches exactly.
        SVG_DPI = 72
        scale = SVG_DPI / 25.4      # SVG user-units per mm
        width_px  = int(page_w_mm * scale)
        height_px = int(page_h_mm * scale)

        # ── Configure QSvgGenerator ───────────────────────────────────────
        generator = QSvgGenerator()
        generator.setFileName(output_path)
        generator.setSize(QSize(width_px, height_px))
        generator.setViewBox(QRectF(0, 0, width_px, height_px))
        generator.setResolution(SVG_DPI)
        generator.setTitle(project.name or "Figure")
        generator.setDescription("Generated by ImageLayoutManager")

        # ── Paint ─────────────────────────────────────────────────────────
        painter = QPainter()
        painter.begin(generator)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        painter.setRenderHint(QPainter.RenderHint.TextAntialiasing)
        painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform)

        # White background (matches raster exporter behaviour)
        painter.fillRect(QRectF(0, 0, width_px, height_px), QColor("white"))

        # Shift origin so the export region maps to (0, 0)
        if region_dx_mm or region_dy_mm:
            painter.translate(-region_dx_mm * scale, -region_dy_mm * scale)

        try:
            ImageExporter._paint_scene(painter, project, layout_result, scale)
        finally:
            painter.end()
