"""
SVG exporter for ImageLayoutManager.

Uses QSvgGenerator as the QPainter target so that the exact same
_paint_scene() pipeline that drives raster and PDF export also drives
SVG output.  This guarantees:

  • All element positions are identical to raster/PDF — they all come
    from LayoutEngine.calculate_layout(), scaled by the same factor.
  • SVG source images are rendered as embedded vector content
    (QSvgRenderer → QPainter → QSvgGenerator preserves vector data).
  • Text renders as SVG <text> nodes (not rasterised outlines).
  • Clip paths, rotations, and blending are handled by Qt natively.

Resolution: the project DPI is forwarded to QSvgGenerator so the
output SVG carries the correct physical dimensions in mm.
"""

from __future__ import annotations

import os
from typing import Optional

from PyQt6.QtCore import QBuffer, QIODevice, QRectF, QSize
import xml.etree.ElementTree as ET
from PyQt6.QtGui import QPainter, QColor
from PyQt6.QtSvg import QSvgGenerator

from src.model.data_model import Project
from src.model.layout_engine import LayoutEngine
from src.export.image_exporter import ImageExporter


class SvgExporter:
    """Export a Project to an SVG file."""

    @staticmethod
    def export(project: Project, output_path: str) -> None:
        """
        Render *project* to *output_path* as an SVG file.

        The output dimensions and DPI match the project settings exactly.
        If project.export_region is set the SVG is clipped to that region,
        mirroring the behaviour of the raster and PDF exporters.
        """
        layout_result = LayoutEngine.calculate_layout(project)
        from src.utils.plot_alignment import resolve_image_placements
        layout_result._image_placements = resolve_image_placements(project, layout_result, strict=True)
        layout_result._image_placements_strict = True

        # ── Resolve export region ─────────────────────────────────────────
        export_region = getattr(project, "export_region", None)
        if export_region is not None:
            page_w_mm = export_region.w_mm
            page_h_mm = export_region.h_mm
            region_dx_mm = export_region.x_mm
            region_dy_mm = export_region.y_mm
        else:
            page_w_mm = project.page_width_mm
            page_h_mm = project.page_height_mm
            region_dx_mm = 0.0
            region_dy_mm = 0.0

        # ── Coordinate scale ──────────────────────────────────────────────
        # QSvgGenerator must be run at 72 DPI (Qt's font reference DPI) so that
        # a font set to P points is emitted as exactly P SVG user-units — no
        # extra DPI inflation.  If we used project.dpi here, Qt would emit
        # font-size = P * (dpi/72) SVG units AND the painter.scale() transform
        # in _draw_text would scale them again, producing text that is
        # (dpi/72)× too large compared to raster/PDF output.
        #
        # Physical dimensions remain correct: the SVG viewBox is in 72-DPI
        # "pixels" and the generator's resolution=72 tells SVG viewers that
        # 1 user-unit = 1/72 inch, so the canvas physical size matches exactly.
        SVG_DPI = 72
        scale = SVG_DPI / 25.4      # SVG user-units per mm
        width_px  = int(page_w_mm * scale)
        height_px = int(page_h_mm * scale)

        # ── Configure QSvgGenerator ───────────────────────────────────────
        buffer = QBuffer()
        buffer.open(QIODevice.OpenModeFlag.WriteOnly)
        generator = QSvgGenerator()
        generator.setOutputDevice(buffer)
        generator.setSize(QSize(width_px, height_px))
        generator.setViewBox(QRectF(0, 0, page_w_mm * scale, page_h_mm * scale))
        generator.setResolution(SVG_DPI)
        generator.setTitle(project.name or "Figure")
        generator.setDescription("Generated by ImageLayoutManager")

        # ── Paint ─────────────────────────────────────────────────────────
        painter = QPainter()
        painter.begin(generator)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        painter.setRenderHint(QPainter.RenderHint.TextAntialiasing)
        painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform)

        # White background (matches raster exporter behaviour)
        background = QRectF(0, 0, page_w_mm * scale, page_h_mm * scale)

        # Shift origin so the export region maps to (0, 0)
        if region_dx_mm or region_dy_mm:
            painter.translate(-region_dx_mm * scale, -region_dy_mm * scale)

        namespace = 'http://www.w3.org/2000/svg'
        layers = []

        def layer(draw, clip=None):
            fragment_buffer = QBuffer()
            fragment_buffer.open(QIODevice.OpenModeFlag.WriteOnly)
            fragment_generator = QSvgGenerator()
            fragment_generator.setOutputDevice(fragment_buffer)
            fragment_generator.setSize(QSize(width_px, height_px))
            fragment_generator.setViewBox(background)
            fragment_generator.setResolution(SVG_DPI)
            fragment_painter = QPainter(fragment_generator)
            fragment_painter._svg_full_source = True
            fragment_painter.setRenderHints(painter.renderHints())
            fragment_painter.translate(-region_dx_mm * scale, -region_dy_mm * scale)
            try:
                draw(fragment_painter)
            finally:
                fragment_painter.end()
            fragment = ET.fromstring(bytes(fragment_buffer.data()))
            prefix = f'layer{len(layers)}_'
            identifiers = {element.get('id'): prefix + element.get('id')
                           for element in fragment.iter() if element.get('id')}
            for element in fragment.iter():
                for key, value in list(element.attrib.items()):
                    if key == 'id':
                        element.set(key, identifiers[value])
                    else:
                        for old, new in identifiers.items():
                            value = value.replace(f'url(#{old})', f'url(#{new})')
                            if key.endswith('href') and value == '#' + old:
                                value = '#' + new
                        element.set(key, value)
            wrapper = ET.Element(f'{{{namespace}}}g')
            if clip is not None:
                clip_id = prefix + 'clip'
                definition = ET.SubElement(wrapper, f'{{{namespace}}}defs')
                clip_path = ET.SubElement(definition, f'{{{namespace}}}clipPath',
                                          {'id': clip_id, 'clipPathUnits': 'userSpaceOnUse'})
                ET.SubElement(clip_path, f'{{{namespace}}}rect', {
                    'x': str((clip.x() - region_dx_mm) * scale),
                    'y': str((clip.y() - region_dy_mm) * scale),
                    'width': str(clip.width() * scale), 'height': str(clip.height() * scale)})
                content = ET.SubElement(wrapper, f'{{{namespace}}}g', {'clip-path': f'url(#{clip_id})'})
            else:
                content = wrapper
            for child in fragment:
                if child.tag.rsplit('}', 1)[-1] in ('defs', 'g'):
                    content.append(child)
            layers.append(wrapper)

        def paint_cell(cell):
            from src.utils.plot_alignment import content_rect
            from src.utils.text_overrides import overrides_for_cell
            content = QRectF(*(value * scale for value in content_rect(
                cell, layout_result.cell_rects[cell.id], project.layout_mode)))
            if content.isEmpty():
                return
            placement = layout_result._image_placements.placements.get(cell.id)
            if placement is not None:
                svg_override, raster_override = overrides_for_cell(
                    project, cell, layout_result, (content.width() / scale, content.height() / scale))
                clip = QRectF(*placement.rect).intersected(QRectF(*placement.clip_rect))
                if not clip.isEmpty():
                    layer(lambda p: ImageExporter._draw_placed_image(
                        p, cell, placement, scale, svg_override, raster_override), clip)
            if placement is not None and getattr(cell, 'scale_bar_enabled', False):
                layer(lambda p: ImageExporter._draw_scale_bar(p, cell,
                    QRectF(*(v * scale for v in placement.rect)), scale, fit_mode_override='contain',
                    typography_mode=getattr(project, 'typography_mode', 'points')))
            if getattr(cell, 'pip_items', []):
                layer(lambda p: ImageExporter._draw_pip_items(p, project, cell, content, scale, placement))

        try:
            ImageExporter._paint_scene(painter, project, layout_result, scale, cell_painter=paint_cell)
        finally:
            painter.end()
        root = ET.fromstring(bytes(buffer.data()))
        root.set('width', f'{page_w_mm}mm')
        root.set('height', f'{page_h_mm}mm')
        root.set('version', '1.1')
        root.attrib.pop('baseProfile', None)
        background_element = ET.Element(f'{{{namespace}}}rect', {
            'x': '0', 'y': '0', 'width': str(background.width()), 'height': str(background.height()),
            'fill': 'white'})
        insertion = next((index for index, child in enumerate(root)
                          if child.tag == f'{{{namespace}}}g'), len(root))
        for child in [background_element, *layers]:
            root.insert(insertion, child)
            insertion += 1
        ET.register_namespace('', namespace)
        ET.register_namespace('xlink', 'http://www.w3.org/1999/xlink')
        ET.ElementTree(root).write(output_path, encoding='utf-8', xml_declaration=True)
